### ISSUE TITLE
No mod in inventory

### ISSUE THREAD

**Issue by Vanellus106** [ChAoSUnItY/Signal#1]
Signal 0.1.2 and Core 0.1.0.2
Using Forge 1.18.2 40.1.0 no mod appears in inventory in Single player mode or Server mode. There is no indication it has loaded and no obvious way of using the mod.

**Comment by ChAoSUnItY** [comment]
Both Signal and Core are only available for fabric, forge support is on the way once fabric version is done

**Comment by Vanellus106** [comment]
Thanks for that. I think you need to make it clearer in Curseforge that this is a Fabric mod.

**Comment by ChAoSUnItY** [comment]
Added disclaimer for forge unsupported, closing issue.
